"""User-entered client and pitch inputs are optional; missing values are never invented."""

from __future__ import annotations

import json
from uuid import UUID

import pytest
from fastapi.testclient import TestClient

from app.auth import create_test_access_token
from app.config import settings
from app.main import create_app
from app.services.data.memory_store import reset_memory_store

OWNER = UUID("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
FULL_INTAKE = {
    "client_web_page": "https://northwind.example",
    "poc_name": "Ada Lovelace",
    "poc_position": "Operations",
    "sales_topic_description": "Warehouse slotting review",
    "about_company": "Family-owned distributor in Hamburg.",
}
INVENTED_PLACEHOLDERS = ("Unknown Company", "Example GmbH", "N/A", "Not provided", "None", "undefined")


def headers() -> dict[str, str]:
    token = create_test_access_token(
        user_id=OWNER, email="sales@example.com", secret=settings.SUPABASE_JWT_SECRET
    )
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture()
def client() -> TestClient:
    reset_memory_store()
    return TestClient(create_app())


def create(client: TestClient, body: dict) -> dict:
    response = client.post("/opportunities", headers=headers(), json=body)
    assert response.status_code == 201, response.text
    return response.json()


def page(paper: dict, page_id: str) -> dict:
    return next(item for item in paper["page_manifest"] if item["id"] == page_id)["content"]


@pytest.mark.parametrize(
    "body",
    [
        {"department": "Sales"},
        {"client_name": "", "opportunity_name": "", "department": "Sales"},
        {"client_name": "", "opportunity_name": "", "department": "Sales", "stage1_intake": None},
        {
            "department": "Sales",
            "stage1_intake": {
                "client_web_page": None,
                "poc_name": None,
                "poc_position": None,
                "sales_topic_description": None,
                "about_company": None,
            },
        },
        {
            "department": "Sales",
            "stage1_intake": {"client_web_page": "", "poc_name": "  ", "about_company": ""},
        },
    ],
)
def test_opportunity_can_be_created_with_every_user_input_empty(client: TestClient, body: dict) -> None:
    created = create(client, body)
    assert created["client_name"] == ""
    assert created["opportunity_name"] == ""
    assert created["stage1_intake"] in (None, {key: None for key in FULL_INTAKE})
    # Identity and state are still generated by the system.
    assert UUID(created["id"])
    assert created["created_by"] == str(OWNER)
    listed = client.get("/opportunities", headers=headers()).json()
    assert [row["id"] for row in listed] == [created["id"]]
    assert listed[0]["client_name"] == ""


def test_each_user_input_is_individually_optional(client: TestClient) -> None:
    for missing in FULL_INTAKE:
        intake = {key: value for key, value in FULL_INTAKE.items() if key != missing}
        created = create(
            client,
            {"client_name": "Northwind", "opportunity_name": "Review", "department": "Sales", "stage1_intake": intake},
        )
        assert created["stage1_intake"][missing] is None
    assert create(client, {"opportunity_name": "Review", "department": "Sales"})["client_name"] == ""
    assert create(client, {"client_name": "Northwind", "department": "Sales"})["opportunity_name"] == ""


def test_empty_client_moves_through_discovery_and_ppt1_without_invented_facts(client: TestClient) -> None:
    opportunity_id = create(client, {"department": "Sales"})["id"]

    workflow = client.get(f"/opportunities/{opportunity_id}/workflow-status", headers=headers()).json()
    assert workflow["current_status"] == "discovery_prepared", "empty client information does not block the workflow"

    generated = client.post(f"/opportunities/{opportunity_id}/discovery-paper/generate", headers=headers())
    assert generated.status_code == 200, generated.text
    paper = generated.json()
    assert paper["status"] == "ready"
    assert paper["schema_version"] == "2.0"
    assert paper["generation"]["specificity"] == "generic"
    assert len(paper["page_manifest"]) > 7

    # Missing input stays missing: nothing is filled in on the user's behalf.
    assert paper["intake_context"] == {
        "client_name": "",
        "contact_name": None,
        "website_url": None,
        "meeting_purpose": "",
        "meeting_purpose_source": "unavailable",
        "additional_information": None,
    }
    research = paper["analysis"]["research"]
    assert research["known_facts"] == []
    assert research["company_profile"] == {"text": None, "origin": "UNKNOWN"}
    assert research["web_research"]["performed"] is False
    assert research["unknown_facts"][:4] == ["Company name", "Contact person", "Website", "Meeting purpose"]
    assert paper["analysis"]["provenance"]["customer_facts_origin"] == "none"
    assert page(paper, "cover")["title"] == "AI opportunity analysis"
    assert "generic discussion basis" in page(paper, "contents")["scope_note"]
    assert "No company profile is available" in page(paper, "ch-overview")["paragraphs"][0]
    rendered = json.dumps(paper)
    for placeholder in INVENTED_PLACEHOLDERS:
        assert f'"{placeholder}"' not in rendered
    for invented in ("GmbH", "revenue of", "headquartered", "founded in", "employees at"):
        assert invented not in rendered

    approved = client.post(f"/opportunities/{opportunity_id}/discovery-paper/approve", headers=headers())
    assert approved.status_code == 200, approved.text

    # No client document was uploaded and none is required.
    outputs = client.post(f"/opportunities/{opportunity_id}/stage1-outputs/generate", headers=headers())
    assert outputs.status_code == 200, outputs.text
    assert outputs.json()["outputs"]["presentation"]["status"] in {"ready", "queued", "generating"}


def test_empty_flow_is_deterministic_in_fixture_mode(client: TestClient) -> None:
    def pages() -> list:
        opportunity_id = create(client, {"department": "Sales"})["id"]
        paper = client.post(f"/opportunities/{opportunity_id}/discovery-paper/generate", headers=headers()).json()
        return [(item["id"], item["type"], item["content"]) for item in paper["page_manifest"]]

    assert pages() == pages()


def test_provided_values_are_still_validated(client: TestClient) -> None:
    for bad_url in ("northwind", "ftp://northwind.example", "https://user:pw@northwind.example", "http://"):
        response = client.post(
            "/opportunities",
            headers=headers(),
            json={"department": "Sales", "stage1_intake": {"client_web_page": bad_url}},
        )
        assert response.status_code == 422, bad_url
    too_long = client.post(
        "/opportunities", headers=headers(), json={"client_name": "x" * 501, "department": "Sales"}
    )
    assert too_long.status_code == 422
    unknown_field = client.post(
        "/opportunities",
        headers=headers(),
        json={"department": "Sales", "stage1_intake": {"poc_email": "ada@example.com"}},
    )
    assert unknown_field.status_code == 422
    # Internal fields keep their rules.
    assert client.post("/opportunities", headers=headers(), json={"department": ""}).status_code == 422
    assert client.post("/opportunities", json={"department": "Sales"}).status_code == 401


def test_populated_client_still_flows_and_keeps_its_data(client: TestClient) -> None:
    opportunity_id = create(
        client,
        {
            "client_name": "Northwind GmbH",
            "opportunity_name": "Slotting review",
            "department": "Sales",
            "stage1_intake": FULL_INTAKE,
        },
    )["id"]
    paper = client.post(f"/opportunities/{opportunity_id}/discovery-paper/generate", headers=headers()).json()
    assert paper["status"] == "ready"
    assert paper["generation"]["specificity"] == "company"
    assert page(paper, "cover")["title"] == "AI opportunities for Northwind GmbH"
    facts = {fact["label"]: fact for fact in paper["analysis"]["research"]["known_facts"]}
    assert {label: fact["value"] for label, fact in facts.items()} == {
        "Company name": "Northwind GmbH",
        "Contact person": "Ada Lovelace",
        "Website": "https://northwind.example",
        "Meeting purpose": "Warehouse slotting review",
        "Additional information": "Family-owned distributor in Hamburg.",
    }
    assert {fact["origin"] for fact in facts.values()} == {"USER_INPUT"}
    assert "Warehouse slotting review" in paper["analysis"]["research"]["core_thesis"]["text"]
    assert "Family-owned distributor in Hamburg." in page(paper, "ch-overview")["paragraphs"][0]
    assert client.post(f"/opportunities/{opportunity_id}/discovery-paper/approve", headers=headers()).status_code == 200
    outputs = client.post(f"/opportunities/{opportunity_id}/stage1-outputs/generate", headers=headers())
    assert outputs.status_code == 200, outputs.text


def test_names_can_be_cleared_and_set_later(client: TestClient) -> None:
    opportunity_id = create(client, {"client_name": "Northwind", "opportunity_name": "Review", "department": "Sales"})["id"]
    cleared = client.patch(
        f"/opportunities/{opportunity_id}", headers=headers(), json={"client_name": "", "opportunity_name": ""}
    )
    assert cleared.status_code == 200, cleared.text
    assert (cleared.json()["client_name"], cleared.json()["opportunity_name"]) == ("", "")
    named = client.patch(f"/opportunities/{opportunity_id}", headers=headers(), json={"client_name": "Northwind AG"})
    assert named.json()["client_name"] == "Northwind AG"
